version: 2
jobs:
  build:
    docker:
      - image: java:8

    steps:
      - checkout

      - run:
          name: Tests 2015
          command: ./gradlew test -Pyear=2015

#      - run:
#          name: Tests 2016
#          command: ./gradlew test -Pyear=2016

      - run:
          name: Tests 2017
          command: ./gradlew test -Pyear=2017

      - run:
          name: Tests 2018
          command: ./gradlew test -Pyear=2018

      - run:
          name: Tests 2019
          command: ./gradlew test -Pyear=2019

      - run:
          name: Tests 2020
          command: ./gradlew test -Pyear=2020
