version: 2
jobs:
  build:
    docker:
      - image: eclipse-temurin:17-jammy

    steps:
      - checkout

      - run:
          name: Tests 2024
          command: ./gradlew :advent-of-code-2024:test -Plowmemory

      - run:
          name: Tests 2022
          command: ./gradlew :advent-of-code-2022:test -Plowmemory

      - run:
          name: Tests 2021
          command: ./gradlew :advent-of-code-2021:test -Plowmemory

      - run:
          name: Tests 2020
          command: ./gradlew :advent-of-code-2020:test -Plowmemory

      - run:
          name: Tests 2019
          command: ./gradlew :advent-of-code-2019:test -Plowmemory

      - run:
          name: Tests 2018
          command: ./gradlew :advent-of-code-2018:test -Plowmemory

      - run:
          name: Tests 2017
          command: ./gradlew :advent-of-code-2017:test -Plowmemory

      - run:
          name: Tests 2016
          command: ./gradlew :advent-of-code-2016:test -Plowmemory

      - run:
          name: Tests 2015
          command: ./gradlew :advent-of-code-2015:test -Plowmemory
